package snmp.entity;
// Generated 06-jun-2016 12:20:31 by Hibernate Tools 4.3.1



/**
 * Dispositivos generated by hbm2java
 */
public class Dispositivos  implements java.io.Serializable {


     private String ip;
     private String name;
     private String descripcion;

    public Dispositivos() {
    }

	
    public Dispositivos(String ip) {
        this.ip = ip;
    }
    public Dispositivos(String ip, String name, String descripcion) {
       this.ip = ip;
       this.name = name;
       this.descripcion = descripcion;
    }
   
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


